name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build ./bibliothek/bibliothek.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./bibliothek/bibliothek.csproj --configuration Release --no-restore --output ./publish/
      
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        # Artifact name
        name: website
        # Destination path
        path: ./publish/
